### ISSUE TITLE
Simulating INT call

### ISSUE THREAD

**Issue by wqweto** [PeterSwinkels/Memory-Dumping-TSR-for-MS-DOS#1]
JFYI, instead of redirecting interrupt 8 to 0xFF you can store its original address in a member variable (e.g. `orig_handler`) and later forward/call it with something like this
```
pushf
call far [orig_handler]
```
This works because and the final `iret` in an interrupt handler is effectively a `retf` followed by `popf`. More info in [this](https://stackoverflow.com/questions/60383360/assembly-call-interrupt-based-on-register-value) SO question.

This prevents crashes if interrupt 0xFF is used by some other TSR/driver or some other application of yours -- keeping original handler in a local variable scales better :-))

**Comment by PeterSwinkels** [comment]
Hi,

Thank you for your suggestion. I will look into it.

Peter

________________________________
From: Vladimir Vissoultchev ***@***.***>
Sent: Thursday, October 7, 2021 8:17 AM
To: PeterSwinkels/Memory-Dumping-TSR-for-MS-DOS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PeterSwinkels/Memory-Dumping-TSR-for-MS-DOS] Simulating INT call (#1)


JFYI, instead of redirecting interrupt 8 to 0xFF you can store its original address in a member variable (e.g. orig_handler) and later forward/call it with something like this

pushf
call far [orig_handler]


This works because and the final iret in an interrupt handler is effectively a retf followed by popf. More info in this<https://stackoverflow.com/questions/60383360/assembly-call-interrupt-based-on-register-value> SO question.

This prevents crashes if interrupt 0xFF is used by some other TSR/driver or some other application of yours -- keeping original handler in a local variable scales better :-))

**Comment by PeterSwinkels** [comment]
I have a question: the code you linked to doesn't clear the interrupt and trap flags unlike the INT opcode. Now I could add a CLI instruction, but there is no easy way to clear the trap flag. Couldn't this cause issues?

**Comment by wqweto** [comment]
I wouldn't worry about these flags as your handler is already executed in response to INT 8 so you already have these flags set (that is cleared) on your handler by the INT 8 code that invoked your handler so just forwarding to original handler with `call far` inherts the flags from your handler as long as you don't fiddle with these explicitly in your code.

**Comment by PeterSwinkels** [comment]
Hi,

I tried modifying the program as you suggested. Now it freezes after displaying the startup info and activated message. I can't find any mistakes in my code. Would you mind looking at it? I can upload a copy to Google Drive or something like that.

**Comment by PeterSwinkels** [comment]
I decided to post the modified code at vbforums: https://www.vbforums.com/forumdisplay.php?17-Assembly

**Comment by PeterSwinkels** [comment]
I updated the program and am going to close the issue. Thank you!
